# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Archivos del Sistema\Documentos\Escuela\Programación Lógica y Funcional\Proyecto\Buscador.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.resize(810, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(True)
        Form.setStyleSheet("")
        self.verticalWidget = QtWidgets.QWidget(Form)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 811, 541))
        self.verticalWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalWidget.setStyleSheet("background-image: url(Menu3.png)")
        self.verticalWidget.setObjectName("verticalWidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.vboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(10, 1, 10, 0)
        self.vboxlayout.setSpacing(3)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_7 = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(600, 0))
        self.label_7.setMaximumSize(QtCore.QSize(1052, 119))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-image: url(tr.png)\n"
"\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("d:\\Archivos del Sistema\\Documentos\\Escuela\\Programación Lógica y Funcional\\Proyecto\\Sin título-2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.vboxlayout.addWidget(self.label_7)
        self.gridFrame_2 = QtWidgets.QFrame(self.verticalWidget)
        self.gridFrame_2.setStyleSheet("background-image: url(Tr.png)")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridFrame = QtWidgets.QFrame(self.gridFrame_2)
        self.gridFrame.setMaximumSize(QtCore.QSize(700, 4000))
        self.gridFrame.setStyleSheet("background-image: url(Menu4.png);\n"
"")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 7, 43);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 6, 0, 1, 1)
        self.Clasificacion = QtWidgets.QComboBox(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clasificacion.sizePolicy().hasHeightForWidth())
        self.Clasificacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.Clasificacion.setFont(font)
        self.Clasificacion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Clasificacion.setStyleSheet("selection-background-color: blue;border-width: 2px;\n"
"background-image: url(Tr.png);\n"
"background-color: white;\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: White;\n"
"font: bold 20px;\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.Clasificacion.setObjectName("Clasificacion")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.gridLayout_9.addWidget(self.Clasificacion, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 7, 43);\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 7, 43);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 7, 43);\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.Motivo = QtWidgets.QComboBox(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Motivo.sizePolicy().hasHeightForWidth())
        self.Motivo.setSizePolicy(sizePolicy)
        self.Motivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Motivo.setStyleSheet("selection-background-color: blue;border-width: 2px;\n"
"background-image: url(Tr.png);\n"
"background-color: white;\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: White;\n"
"font: bold 20px;\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.Motivo.setPlaceholderText("")
        self.Motivo.setObjectName("Motivo")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.gridLayout_9.addWidget(self.Motivo, 5, 0, 1, 1)
        self.Edad = QtWidgets.QComboBox(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edad.sizePolicy().hasHeightForWidth())
        self.Edad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.Edad.setFont(font)
        self.Edad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Edad.setStyleSheet("selection-background-color: blue;border-width: 2px;\n"
"background-image: url(Tr.png);\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: White;\n"
"font: bold 20px;\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.Edad.setIconSize(QtCore.QSize(16, 16))
        self.Edad.setObjectName("Edad")
        self.Edad.addItem("")
        self.Edad.addItem("")
        self.Edad.addItem("")
        self.gridLayout_9.addWidget(self.Edad, 1, 0, 1, 1)
        self.GeneroP = QtWidgets.QComboBox(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneroP.sizePolicy().hasHeightForWidth())
        self.GeneroP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.GeneroP.setFont(font)
        self.GeneroP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GeneroP.setStyleSheet("selection-background-color: blue;border-width: 2px;\n"
"background-image: url(Tr.png);\n"
"background-color: white;\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: White;\n"
"font: bold 20px;\n"
"min-width: 10em;\n"
"padding: 6px;")
        self.GeneroP.setObjectName("GeneroP")
        self.GeneroP.addItem("")
        self.GeneroP.addItem("")
        self.GeneroP.addItem("")
        self.gridLayout_9.addWidget(self.GeneroP, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.gridFrame, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.gridFrame_2)
        self.widget.setStyleSheet("background-image: url(Tr.png);width: 2px;\n"
"    border-radius: 25px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LabelNombre_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.LabelNombre_2.setFont(font)
        self.LabelNombre_2.setStyleSheet("background-image: url(Tr.png);    border-radius: 5px;color: rgb(255, 152, 56);")
        self.LabelNombre_2.setText("")
        self.LabelNombre_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNombre_2.setObjectName("LabelNombre_2")
        self.gridLayout_2.addWidget(self.LabelNombre_2, 2, 1, 1, 1)
        self.LabelNombre = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.LabelNombre.setFont(font)
        self.LabelNombre.setStyleSheet("background-image: url(Tr.png);    border-radius: 5px;color: rgb(255, 152, 56);")
        self.LabelNombre.setText("")
        self.LabelNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNombre.setObjectName("LabelNombre")
        self.gridLayout_2.addWidget(self.LabelNombre, 0, 1, 1, 1)
        self.labelImagen = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImagen.sizePolicy().hasHeightForWidth())
        self.labelImagen.setSizePolicy(sizePolicy)
        self.labelImagen.setStyleSheet("background-image: url(Tr.png);    border-radius: 5px; weight: 169px; lenght: 178px\n"
"")
        self.labelImagen.setText("")
        self.labelImagen.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImagen.setObjectName("labelImagen")
        self.gridLayout_2.addWidget(self.labelImagen, 0, 3, 1, 1)
        self.label_Explicacion2 = QtWidgets.QLabel(self.widget)
        self.label_Explicacion2.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Explicacion2.setFont(font)
        self.label_Explicacion2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_Explicacion2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Explicacion2.setText("")
        self.label_Explicacion2.setScaledContents(True)
        self.label_Explicacion2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Explicacion2.setWordWrap(True)
        self.label_Explicacion2.setObjectName("label_Explicacion2")
        self.gridLayout_2.addWidget(self.label_Explicacion2, 3, 3, 1, 1)
        self.labelImagen_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImagen_2.sizePolicy().hasHeightForWidth())
        self.labelImagen_2.setSizePolicy(sizePolicy)
        self.labelImagen_2.setStyleSheet("background-image: url(Tr.png);    border-radius: 5px; weight: 169px; lenght: 178px\n"
"")
        self.labelImagen_2.setText("")
        self.labelImagen_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImagen_2.setObjectName("labelImagen_2")
        self.gridLayout_2.addWidget(self.labelImagen_2, 2, 3, 1, 1)
        self.Label_Explicacion = QtWidgets.QLabel(self.widget)
        self.Label_Explicacion.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_Explicacion.setFont(font)
        self.Label_Explicacion.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.Label_Explicacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_Explicacion.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Explicacion.setText("")
        self.Label_Explicacion.setScaledContents(True)
        self.Label_Explicacion.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Explicacion.setWordWrap(True)
        self.Label_Explicacion.setObjectName("Label_Explicacion")
        self.gridLayout_2.addWidget(self.Label_Explicacion, 1, 3, 1, 1)
        self.boton1 = QtWidgets.QPushButton(self.widget)
        self.boton1.setEnabled(True)
        self.boton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton1.setStyleSheet(" border-style: outset;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"border: 1px black solid;\n"
"color: black;\n"
"background-color: orange;\n"
"padding: 6px;\n"
"")
        self.boton1.setCheckable(False)
        self.boton1.setChecked(False)
        self.boton1.setObjectName("boton1")
        self.gridLayout_2.addWidget(self.boton1, 1, 1, 1, 1)
        self.boton2 = QtWidgets.QPushButton(self.widget)
        self.boton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton2.setStyleSheet(" border-style: outset;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"border: 1px black solid;\n"
"color: black;\n"
"background-color: orange;\n"
"padding: 6px;\n"
"")
        self.boton2.setObjectName("boton2")
        self.gridLayout_2.addWidget(self.boton2, 3, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Boton_Buscar = QtWidgets.QPushButton(self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Boton_Buscar.sizePolicy().hasHeightForWidth())
        self.Boton_Buscar.setSizePolicy(sizePolicy)
        self.Boton_Buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Buscar.setStyleSheet("color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"background-image: url(Menu2.png)")
        self.Boton_Buscar.setObjectName("Boton_Buscar")
        self.horizontalLayout.addWidget(self.Boton_Buscar)
        self.Expl = QtWidgets.QPushButton(self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Expl.sizePolicy().hasHeightForWidth())
        self.Expl.setSizePolicy(sizePolicy)
        self.Expl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Expl.setStyleSheet("color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"background-image: url(Menu2.png)")
        self.Expl.setObjectName("Expl")
        self.horizontalLayout.addWidget(self.Expl)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.vboxlayout.addWidget(self.gridFrame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sistema Experto en Anime"))
        self.label_2.setText(_translate("Form", "¿Que genero deseas ver?"))
        self.Clasificacion.setItemText(0, _translate("Form", "Accion"))
        self.Clasificacion.setItemText(1, _translate("Form", "Romance"))
        self.Clasificacion.setItemText(2, _translate("Form", "Comedia"))
        self.Clasificacion.setItemText(3, _translate("Form", "Drama"))
        self.label_3.setText(_translate("Form", "¿Cual es la trama del anime?"))
        self.label.setText(_translate("Form", "¿Cual es la edad de la persona?"))
        self.label_4.setText(_translate("Form", "¿Cantidad de capítulos?"))
        self.Motivo.setCurrentText(_translate("Form", "Fantasía"))
        self.Motivo.setItemText(0, _translate("Form", "Fantasía"))
        self.Motivo.setItemText(1, _translate("Form", "Ciencia Ficcion"))
        self.Motivo.setItemText(2, _translate("Form", "Misterio"))
        self.Motivo.setItemText(3, _translate("Form", "Vida Diaria"))
        self.Edad.setItemText(0, _translate("Form", "Niños"))
        self.Edad.setItemText(1, _translate("Form", "Jovenes"))
        self.Edad.setItemText(2, _translate("Form", "Adultos"))
        self.GeneroP.setItemText(0, _translate("Form", "30 - 150"))
        self.GeneroP.setItemText(1, _translate("Form", "150+"))
        self.GeneroP.setItemText(2, _translate("Form", "500+"))
        self.boton1.setText(_translate("Form", "Ver explicación"))
        self.boton2.setText(_translate("Form", "Ver explicación"))
        self.Boton_Buscar.setText(_translate("Form", "Buscar"))
        self.Expl.setText(_translate("Form", "Modo Experto"))
