# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Archivos del Sistema\Documentos\Escuela\Programación Lógica y Funcional\Proyecto\Ingreso.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formulario(object):
    def setupUi(self, Formulario):
        Formulario.setObjectName("Formulario")
        Formulario.setWindowModality(QtCore.Qt.WindowModal)
        Formulario.setEnabled(True)
        Formulario.resize(820, 665)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Formulario.sizePolicy().hasHeightForWidth())
        Formulario.setSizePolicy(sizePolicy)
        Formulario.setAutoFillBackground(True)
        Formulario.setStyleSheet("")
        self.Contenido = QtWidgets.QWidget(Formulario)
        self.Contenido.setGeometry(QtCore.QRect(0, 30, 811, 511))
        self.Contenido.setStyleSheet("background-image: url(Menu3.png)")
        self.Contenido.setObjectName("Contenido")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.Contenido)
        self.vboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(10, 1, 10, 0)
        self.vboxlayout.setSpacing(3)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridWidget_2 = QtWidgets.QWidget(self.Contenido)
        self.gridWidget_2.setStyleSheet("background-image: url(Tr.png)")
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.gridWidget_2)
        self.widget.setStyleSheet("background-image: url(Tr.png)")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelImagen = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImagen.sizePolicy().hasHeightForWidth())
        self.labelImagen.setSizePolicy(sizePolicy)
        self.labelImagen.setStyleSheet("background-image: url(Tr.png);    border-radius: 5px; weight: 166px")
        self.labelImagen.setText("")
        self.labelImagen.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImagen.setObjectName("labelImagen")
        self.gridLayout_2.addWidget(self.labelImagen, 0, 0, 1, 1)
        self.Imagen = QtWidgets.QPushButton(self.widget)
        self.Imagen.setStyleSheet("color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"background-image: url(Menu2.png)")
        self.Imagen.setObjectName("Imagen")
        self.gridLayout_2.addWidget(self.Imagen, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.widget, 3, 1, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.gridWidget_2)
        self.gridWidget.setStyleSheet("background-image: url(Menu4.png);\n"
"    border-radius: 25px;")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Nombre = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nombre.sizePolicy().hasHeightForWidth())
        self.Nombre.setSizePolicy(sizePolicy)
        self.Nombre.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    placeholder: \"Nombre del Anime\";\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-color: White;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.Nombre.setText("")
        self.Nombre.setObjectName("Nombre")
        self.gridLayout_9.addWidget(self.Nombre, 10, 2, 1, 1)
        self.GeneroP = QtWidgets.QComboBox(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneroP.sizePolicy().hasHeightForWidth())
        self.GeneroP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.GeneroP.setFont(font)
        self.GeneroP.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: White;\n"
"    font: bold 20px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.GeneroP.setEditable(True)
        self.GeneroP.setObjectName("GeneroP")
        self.GeneroP.addItem("")
        self.GeneroP.setItemText(0, "")
        self.GeneroP.addItem("")
        self.GeneroP.addItem("")
        self.GeneroP.addItem("")
        self.gridLayout_9.addWidget(self.GeneroP, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("background-image: url(Tr.png)")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet("background-image: url(Tr.png)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("background-image: url(Tr.png)")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("background-image: url(Tr.png)")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("background-image: url(Tr.png)")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("background-image: url(Tr.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 1, 2, 1, 1)
        self.Clasificacion = QtWidgets.QComboBox(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clasificacion.sizePolicy().hasHeightForWidth())
        self.Clasificacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.Clasificacion.setFont(font)
        self.Clasificacion.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: White;\n"
"    font: bold 20px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.Clasificacion.setEditable(True)
        self.Clasificacion.setObjectName("Clasificacion")
        self.Clasificacion.addItem("")
        self.Clasificacion.setItemText(0, "")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.Clasificacion.addItem("")
        self.gridLayout_9.addWidget(self.Clasificacion, 6, 2, 1, 1)
        self.Explicacion = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Explicacion.sizePolicy().hasHeightForWidth())
        self.Explicacion.setSizePolicy(sizePolicy)
        self.Explicacion.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-color: White;\n"
"    font: bold 14px;\n"
"    placeholder: \"Explicacion\";\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.Explicacion.setText("")
        self.Explicacion.setObjectName("Explicacion")
        self.gridLayout_9.addWidget(self.Explicacion, 8, 2, 1, 1)
        self.Edad = QtWidgets.QComboBox(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edad.sizePolicy().hasHeightForWidth())
        self.Edad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.Edad.setFont(font)
        self.Edad.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: White;\n"
"    font: bold 20px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.Edad.setEditable(True)
        self.Edad.setIconSize(QtCore.QSize(16, 16))
        self.Edad.setObjectName("Edad")
        self.Edad.addItem("")
        self.Edad.setItemText(0, "")
        self.Edad.addItem("")
        self.Edad.addItem("")
        self.Edad.addItem("")
        self.gridLayout_9.addWidget(self.Edad, 0, 2, 1, 1)
        self.Motivo = QtWidgets.QComboBox(self.gridWidget)
        self.Motivo.setStyleSheet("selection-background-color: blue;border-width: 2px;background-image: url(Tr.png);background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: White;\n"
"    font: bold 20px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.Motivo.setEditable(True)
        self.Motivo.setObjectName("Motivo")
        self.Motivo.addItem("")
        self.Motivo.setItemText(0, "")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.Motivo.addItem("")
        self.gridLayout_9.addWidget(self.Motivo, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(Tr.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gridWidget, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gridWidget_2, 0, 0, 1, 1)
        self.vboxlayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Guardar = QtWidgets.QPushButton(self.Contenido)
        self.Guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Guardar.setStyleSheet("color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    max-width: 25px;\n"
"    padding: 6px;\n"
"background-image: url(Menu2.png)")
        self.Guardar.setObjectName("Guardar")
        self.horizontalLayout_2.addWidget(self.Guardar)
        self.volver = QtWidgets.QPushButton(self.Contenido)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volver.sizePolicy().hasHeightForWidth())
        self.volver.setSizePolicy(sizePolicy)
        self.volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"background-image: url(Menu2.png)")
        self.volver.setObjectName("volver")
        self.horizontalLayout_2.addWidget(self.volver)
        self.vboxlayout.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(Formulario)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 800, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(800, 70))
        self.label_7.setMaximumSize(QtCore.QSize(500, 40))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-image: url(Tr.png)")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("d:\\Archivos del Sistema\\Documentos\\Escuela\\Programación Lógica y Funcional\\Proyecto\\Sin título-2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Formulario)
        QtCore.QMetaObject.connectSlotsByName(Formulario)

    def retranslateUi(self, Formulario):
        _translate = QtCore.QCoreApplication.translate
        Formulario.setWindowTitle(_translate("Formulario", "Agregar Rama"))
        self.Imagen.setText(_translate("Formulario", "Imagen"))
        self.Nombre.setPlaceholderText(_translate("Formulario", "Nombre del anime"))
        self.GeneroP.setItemText(1, _translate("Formulario", "30 - 150"))
        self.GeneroP.setItemText(2, _translate("Formulario", "150+"))
        self.GeneroP.setItemText(3, _translate("Formulario", "500+"))
        self.label_12.setText(_translate("Formulario", "Anime"))
        self.label_4.setText(_translate("Formulario", "¿Cantidad de capítulos?"))
        self.label_5.setText(_translate("Formulario", "Explicación"))
        self.label_2.setText(_translate("Formulario", "¿Que genero deseas ver?"))
        self.label_3.setText(_translate("Formulario", "¿Cual es la trama del anime?"))
        self.Clasificacion.setItemText(1, _translate("Formulario", "Accion"))
        self.Clasificacion.setItemText(2, _translate("Formulario", "Romance"))
        self.Clasificacion.setItemText(3, _translate("Formulario", "Comedia"))
        self.Clasificacion.setItemText(4, _translate("Formulario", "Drama"))
        self.Explicacion.setPlaceholderText(_translate("Formulario", "Explicación"))
        self.Edad.setItemText(1, _translate("Formulario", "Niños"))
        self.Edad.setItemText(2, _translate("Formulario", "Jovenes"))
        self.Edad.setItemText(3, _translate("Formulario", "Adultos"))
        self.Motivo.setItemText(1, _translate("Formulario", "Fantasía"))
        self.Motivo.setItemText(2, _translate("Formulario", "Ciencia Ficcion"))
        self.Motivo.setItemText(3, _translate("Formulario", "Misterio"))
        self.Motivo.setItemText(4, _translate("Formulario", "Vida diaria"))
        self.label.setText(_translate("Formulario", "¿Cual es la edad de la persona?"))
        self.Guardar.setText(_translate("Formulario", "Guardar"))
        self.volver.setText(_translate("Formulario", "Volver"))
